availability_zone1 = "us-east-1a"
availability_zone2 = "us-east-1b"
availability_zone3 = "us-east-1c"
aws_profile = "dev"
aws_region = "us-east-1"
subnet1_cidr_block = "10.0.1.0/24"
subnet2_cidr_block = "10.0.2.0/24"
subnet3_cidr_block = "10.0.3.0/24"
vpc_cidr_block = "10.0.0.0/16"
vpc_name = "dev"

domain_name = "syriii.me"
ami_id = "ami-0c097acf78b90ee5c"
key_name = "dev_key"
public_key_path = "/home/shangrui/Desktop/dev_key/dev_key.pub"

aws_access_key = "AKIAWWNJIPHBBBYZ364I"
aws_secret_key = "0BziIv7MyaBAwoU4KdS+A4iCSMLYNW5w+RtDWH4m/9B"
tomcat_log_dir = "/home/centos"
