availability_zone1 = "us-east-1a"
availability_zone2 = "us-east-1d"
availability_zone3 = "us-east-1e"
aws_profile = "prod"
aws_region = "us-east-1"
subnet1_cidr_block = "10.0.1.0/24"
subnet2_cidr_block = "10.0.2.0/24"
subnet3_cidr_block = "10.0.3.0/24"
vpc_cidr_block = "10.0.0.0/16"
vpc_name = "prod"


domain_name = "syriii.me"
ami_id = "ami-0cf986d229cbce35f"
key_name = "dev_key"
public_key_path = "~/Desktop/dev_key/dev_key.pub"

aws_access_key = "AKIAWP7XOH7ZMWLBIROZ"
aws_secret_key = "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"
tomcat_log_dir = "/home/centos"
